<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;



use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

// Create a shortcut for params.
$params = $this->item->params;
$canEdit = $this->item->params->get('access-edit');
$info = $params->get('info_block_position', 0);


// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate = Factory::getDate()->format('Y-m-d H:i:s');
$isUnpublished = ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED || $this->item->publish_up > $currentDate)
    || ($this->item->publish_down < $currentDate && $this->item->publish_down !== null);


?>
<div class="events-info mt-3">
    <div class="events-article-image">
        <?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
    </div>
    <div class="item-content events-articles">
        <?php if ($isUnpublished): ?>
            <div class="system-unpublished">
            <?php endif; ?>

            <?php
            // Import route helper if not already
            JLoader::register('ContentHelperRoute', JPATH_SITE . '/components/com_content/helpers/route.php');

            $link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->id, $this->item->catid));
            ?>
            <div class="event-item-title">
                <h2>
                    <a href="<?php echo $link; ?>">
                        <?php echo htmlspecialchars($this->item->title, ENT_QUOTES, 'UTF-8'); ?>
                    </a>
                </h2>
            </div>




            <?php if ($canEdit): ?>
                <?php echo LayoutHelper::render('joomla.content.icons', ['params' => $params, 'item' => $this->item]); ?>
            <?php endif; ?>

            <?php // @todo Not that elegant would be nice to group the params ?>

            <?php $useDefList = ($params->get('show_modify_date') || $params->get('show_author') || $params->get('show_publish_date') || $params->get('show_create_date')
                || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $assocParam); ?>


            <?php if ($useDefList && ($info == 0 || $info == 2)): ?>
                <?php // echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above']); ?>
            <?php endif; ?>



            <?php if (!$params->get('show_intro')): ?>
                <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
                <?php //echo $this->item->event->afterDisplayTitle; ?>
            <?php endif; ?>

            <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
            <?php //echo $this->item->event->beforeDisplayContent; ?>

            <div class="event-item-content">   
                 <?php
                    $introText = strip_tags($this->item->introtext);
                    if (strlen($introText) > 150) {
                        echo substr($introText, 0, 150) . '...';
                    }
                    else {
                        echo $introText;
                    }
                ?>
            </div>

			<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
                <div class="event-tags"> 
                    <?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

                    <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
                </div>
            <?php endif; ?>

            <?php if ($info == 1 || $info == 2): ?>
                <?php if ($useDefList): ?>
                    <?php echo LayoutHelper::render('joomla.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'below']); ?>
                <?php endif; ?>
                <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)): ?>
                    <?php echo LayoutHelper::render('joomla.content.tags', $this->item->tags->itemTags); ?>
                <?php endif; ?>
            <?php endif; ?>

            <?php if ($params->get('show_readmore') && $this->item->readmore):
                if ($params->get('access-view')):
                    $link = Route::_(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
                else:
                    $menu = Factory::getApplication()->getMenu();
                    $active = $menu->getActive();
                    $itemId = $active->id;
                    $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
                    $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
                endif; ?>

                <?php echo LayoutHelper::render('joomla.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>

            <?php endif; ?>
            <div class="event-author-date">
                <?php
                // if author-name is empty else Tekdi Author 
                $author = !empty($this->item->author) ? $this->item->author : 'Tekdi Author';

                // Published date
                $date = !empty($this->item->publish_up) ? date('d M Y', strtotime($this->item->publish_up)) : '';

                echo $author . ' | ' . $date;
                ?>

            </div>
            <?php if ($isUnpublished): ?>
            </div>
        <?php endif; ?>

        <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
        <?php echo $this->item->event->afterDisplayContent; ?>
    </div>
</div>
<style>
.events-item .events-info .events-articles .event-author-date {
  font-size: 14px !important;
  font-weight: 300 !important;
  line-height: 22px !important;
  color: #484848 !important;
  padding-top: 10px !important;
}
</style>