<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_tags
 *
 * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Tags\Site\Helper\RouteHelper;

/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = $this->document->getWebAssetManager();
$wa->useScript('com_tags.tag-default');

// Get the user object.
$user = Factory::getUser();

// Check if user is allowed to add/edit based on tags permissions.
// Do we really have to make it so people can see unpublished tags???
$canEdit = $user->authorise('core.edit', 'com_tags');
$canCreate = $user->authorise('core.create', 'com_tags');
$canEditState = $user->authorise('core.edit.state', 'com_tags');
?>
<div class="com-tags__items">
    <?php if (empty($this->items)): ?>
        <div class="alert alert-info">
            <span class="icon-info-circle" aria-hidden="true"></span><span class="visually-hidden">
                <?php echo Text::_('INFO'); ?>
            </span>
            <?php echo Text::_('COM_TAGS_NO_ITEMS'); ?>
        </div>
    <?php else: ?>
     <div class="row">
        <?php foreach ($this->items as $i => $item): ?>
            <?php if ($item->core_state == 0): ?>

            <?php else: ?>

            <?php endif; ?>
            <?php if (($item->type_alias === 'com_users.category') || ($item->type_alias === 'com_banners.category')): ?>
                <h3>
                    <?php echo $this->escape($item->core_title); ?>
                </h3>
            <?php else: ?>


            <?php endif; ?>

            <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
            <?php echo $item->event->afterDisplayTitle; ?>
            <?php $images = json_decode($item->core_images); ?>
            <?php if ($this->params->get('tag_list_show_item_image', 1) == 1 && !empty($images->image_intro)): ?>
            <?php endif; ?>
            <!--<div class="row mb-5 pb-5 tags-card">
                <div class="col-md-3 col-sm-4 col-xs-12 mb-4">
                    <?php echo HTMLHelper::_('image', $images->image_intro, $images->image_intro_alt); ?>
                </div>
                <div class="col-md-9 col-sm-8 col-xs-12">
                    <div class="blog-item-title">
                        <div class="page-header">
                            <h2>
                                <a href="<?php echo Route::_($item->link); ?>">
                                    <?php echo $this->escape($item->core_title); ?>
                                </a>
                            </h2>
                        </div>
                    </div>
                    <?php if ($this->params->get('tag_list_show_item_description', 1)): ?>
                        <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
                        <?php echo $item->event->beforeDisplayContent; ?>
                        <p class="blog-item-content">
                            <?php echo $this->escape($item->core_body); ?>
                            <?php echo HTMLHelper::_('string.truncate', $item->core_body, $this->params->get('tag_list_item_maximum_characters')); ?>
                        </p>
                        <?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
                        <?php echo $item->event->afterDisplayContent; ?>
                    <?php endif; ?>
                </div>
            </div>-->
           
               
              <!--  <div class="col-12 col-md-6 mb-5">
    <div class="tags-card card shadow-sm border-0 h-100">
        <div class="tags-card-img">
            <?php echo HTMLHelper::_('image', $images->image_intro, $images->image_intro_alt, [
        'class' => 'img-fluid w-100 tags-img',
        'loading' => 'lazy'
    ]); ?>
            <?php //echo HTMLHelper::_('image', $images->image_intro, $images->image_intro_alt, ['class' => 'img-fluid w-100']); ?>
        </div>

        <div class="card-body">
            <h3 class="tags-card-title mb-3">
                <a href="<?php echo Route::_($item->link); ?>">
                    <?php echo $this->escape($item->core_title); ?>
                </a>
            </h3>

            <p class="tags-card-desc">
                <?php echo HTMLHelper::_('string.truncate', strip_tags($item->core_body), 160); ?>
            </p>

            <div class="tags-card-meta mt-3">
                <span class="author"><?php echo $item->author; ?></span> |
                <span class="date"><?php echo JHtml::_('date', $item->core_created_time, 'd M Y'); ?></span>
            </div>
        </div>
    </div>
</div>-->

<div class="col-12 col-md-6 mb-5">
    <div class="tags-card card shadow-sm border-0 h-100">

        <div class="tags-card-img">
            <?php 
                $img = !empty($images->image_intro) 
                    ? $images->image_intro 
                    : 'images/default.jpg'; // <- तुमची default image येथे ठेवा
            ?>

            <?php echo HTMLHelper::_('image', $img, $images->image_intro_alt, [
                'class' => 'img-fluid w-100 tags-img',
                'loading' => 'lazy'
            ]); ?>
        </div>

        <div class="card-body">
            <h3 class="tags-card-title mb-3">
                <a href="<?php echo Route::_($item->link); ?>">
                    <?php echo $this->escape($item->core_title); ?>
                </a>
            </h3>

            <!--<p class="tags-card-desc">
                <?php echo HTMLHelper::_('string.truncate', strip_tags($item->core_body), 160); ?>
            </p>

            <div class="tags-card-meta mt-3">
                <span class="author"><?php echo $item->author; ?></span> |
                <span class="date"><?php echo JHtml::_('date', $item->core_created_time, 'd M Y'); ?></span>
            </div>-->
        </div>

    </div>
</div>


        <?php endforeach; ?>
</div>

    <?php endif; ?>
</div>